name: Weapons
main: pw.kaboom.weapons.Main
description: Plugin that implements various kinds of weapons.
version: master

commands:
   weapons:
      aliases: weapon
      description: Gives you a weapon
      usage: /weapons
      permission: weapons.command
